# -*- coding: utf-8 -*-

# Project Euler
# Problem 028: Number Spiral Diagonals
# Runtime : 0 ms

# Prior Mathematical treatment was done in order to assess that there are four series generated by the diagonals of a number spiral
# The sum of the four corners can be given by 3 * (n - 1) ** 2 + n ** 2 + 3 for n >= 3 and 1 for n == 1

import time

def SumofCorners(sizeofgrid):
    return 1 + sum([3 * (n - 1) ** 2 + n ** 2 + 3 for n in range(3,sizeofgrid+1,2)])
       
    
if __name__ == '__main__':
    start_time = time.time()
    print(SumofCorners(1001))
    print('{:2f} seconds'.format(time.time() - start_time)) 

